# Generated by Django 4.2.11 on 2024-04-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialplatform",
            name="facebook_icon",
            field=models.ImageField(blank=True, upload_to="social_icons/"),
        ),
        migrations.AddField(
            model_name="socialplatform",
            name="instagram_icon",
            field=models.ImageField(blank=True, upload_to="social_icons/"),
        ),
        migrations.AddField(
            model_name="socialplatform",
            name="twitter_icon",
            field=models.ImageField(blank=True, upload_to="social_icons/"),
        ),
        migrations.AddField(
            model_name="socialplatform",
            name="youtube_icon",
            field=models.ImageField(blank=True, upload_to="social_icons/"),
        ),
    ]
