# Generated by Django 4.2.11 on 2024-04-14 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_remove_socialplatform_facebook_icon_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SocialPlatform",
        ),
    ]
