# Generated by Django 4.2.11 on 2024-04-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_delete_socialplatform"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("url", models.URLField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome class name (e.g., 'fab fa-facebook')",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
