# Generated by Django 4.2.11 on 2024-04-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_socialplatform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featured",
            name="background_image",
            field=models.ImageField(upload_to="images/background_images/"),
        ),
        migrations.AlterField(
            model_name="featured",
            name="featured_image",
            field=models.ImageField(upload_to="images/featured_images/"),
        ),
        migrations.AlterField(
            model_name="release",
            name="artwork",
            field=models.ImageField(blank=True, upload_to="images/release_artwork/"),
        ),
    ]
