# Generated by Django 4.2.11 on 2024-04-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_alter_featured_background_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="logos/")),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
