# Generated by Django 4.2.11 on 2024-04-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThemeColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("color_code", models.CharField(max_length=7)),
            ],
        ),
    ]
