# Generated by Django 4.2.11 on 2024-04-16 16:36

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_themecolor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="themecolor",
            name="color_code",
        ),
        migrations.AddField(
            model_name="themecolor",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
