# Generated by Django 4.2.11 on 2024-04-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_remove_themecolor_color_code_themecolor_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="themecolor",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
