# Generated by Django 4.2.11 on 2024-04-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_themecolor_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("background_image", models.ImageField(upload_to="tour_backgrounds/")),
                ("is_dark_text", models.BooleanField(default=True)),
            ],
        ),
    ]
