# Generated by Django 4.2.11 on 2024-04-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_tour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logo",
            name="image",
            field=models.ImageField(upload_to="images/logos/"),
        ),
        migrations.AlterField(
            model_name="tour",
            name="background_image",
            field=models.ImageField(upload_to="images/tour_backgrounds/"),
        ),
    ]
