# Generated by Django 4.2.11 on 2024-04-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0012_alter_logo_image_alter_tour_background_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featured",
            name="background_image",
            field=models.ImageField(upload_to="static/images/background_images/"),
        ),
        migrations.AlterField(
            model_name="featured",
            name="featured_image",
            field=models.ImageField(upload_to="static/images/featured_images/"),
        ),
        migrations.AlterField(
            model_name="logo",
            name="image",
            field=models.ImageField(upload_to="static/images/logos/"),
        ),
        migrations.AlterField(
            model_name="release",
            name="artwork",
            field=models.ImageField(
                blank=True, upload_to="static/images/release_artwork/"
            ),
        ),
        migrations.AlterField(
            model_name="tour",
            name="background_image",
            field=models.ImageField(upload_to="static/images/tour_backgrounds/"),
        ),
    ]
